### PR TITLE
Added tooltips and alert info boxes.

### PR DESCRIPTION
**Pull request by Mikkoun**
* New InfoTooltipBtn component for info tooltips all around the app.
* New HelpAlert component for alert type informative/help content.
* Added tooltips all around the app with links redirecting to documentation.

### CODE REVIEW

**Comment by elvijsTDL** [comment]
Granularity set to seconds, tooltip showing day/month 

Screenshot 2022-03-09 at 11 47 35

**Review by kasparkallas — APPROVED** [review]

**Comment by elvijsTDL** [comment]
@Mikkoun 
Can we have these tooltips next to the text, didn't even notice it the first time I opened the page
Screenshot 2022-03-10 at 10 33 17
Screenshot 2022-03-10 at 10 35 30

This message should change depending on the granuality or just type out all of them
Screenshot 2022-03-10 at 10 34 05

No tooltip for the publisher?
Screenshot 2022-03-10 at 10 36 51

Screenshot 2022-03-10 at 10 36 37


Index subscriptions seem to be missing a tooltip
Screenshot 2022-03-10 at 10 46 23
Screenshot 2022-03-10 at 10 45 59

**Comment by vmichalik** [comment]
@Mikkoun looks great! One suggestion - can we look into using a popper or similar component to make the info text on the Streams, Indexes and Events tabs only show on click? The usefulness of that info will steeply drop off from the first time someone sees it, so we shouldn't force it every time.

**Comment by Mikkoun** [comment]
> @Mikkoun looks great! One suggestion - can we look into using a popper or similar component to make the info text on the Streams, Indexes and Events tabs only show on click? The usefulness of that info will steeply drop off from the first time someone sees it, so we shouldn't force it every time.

We tried different solutions with tooltips as well but this alert box seemed to be the best. We could come back to it if it starts to be annoying. There could be a button to close the box but I can't imagine any good solutions to open it again.

**Comment by elvijsTDL** [comment]
@Mikkoun LGTM

**Review by elvijsTDL — APPROVED** [review]

**Review by mariamtava — APPROVED** [review]

**Pull request merged**
