### PR TITLE
GDA fixes & project clean-up

### PR DESCRIPTION
**Pull request by kasparkallas**

### CODE REVIEW

**Comment by elvijsTDL** [comment]
Subgraphs not being up to latest schema on all networks currently breaking most of the GDA related pages  , like [here] , thus breaking some of the tests that need to be re-checked once graphs get re-deployed (https://superfluid-console-git-gda-clean-up-superfluid-finance.vercel.app/avalanche-fuji/pool-members/poolMember-0x9a4a1d83be575f3ec59ff259d65d6fe94f78a3d8-0xc19be11b5f9eac59758f4dbaaad465abb9103a95)
image

**Comment by vmichalik** [comment]
pools should probably be identified by address right? 
CleanShot 2024-01-17 at 10 02 12@2x

**Comment by kasparkallas** [comment]
> pools should probably be identified by address right?

You can see the address in the detail view. But sure, there's value in seeing it in the table to distinguish between the pools.

**Comment by elvijsTDL** [comment]
It does not seem to pick up the latest deployment GDA related stuff e.g. https://superfluid-console-git-gda-clean-up-superfluid-finance.vercel.app/bnb-smart-chain/accounts/0xF9Ce34dFCD3cc92804772F3022AF27bCd5E43Ff2?tab=pools , this wallet is an admin of multiple pools on BSC but none are shown , also the getNetFlow calls keep failing that need to be fixed 
Screenshot 2024-01-24 at 11 43 41

**Review by elvijsTDL — APPROVED** [review]
Will fix test cases in a seperate PR

**Pull request merged**
