### PR TITLE
Network: Celo Mainnet

### PR DESCRIPTION
**Pull request by tokdaniel**

### CODE REVIEW

**Comment by vmichalik** [comment]
@tokdaniel can you add the Celo protocol [deployment addresses](https://github.com/superfluid-finance/metadata/blob/master/main/networks/list.cjs) to this page? https://github.com/superfluid-finance/superfluid-console/blob/network/celo-mainnet/src/redux/protocolContracts.ts

Also, should be celo-mainnet as the slug as in the dashboard and latest metadata version no?

**Comment by tokdaniel** [comment]
> @tokdaniel can you add the Celo protocol [deployment addresses](https://github.com/superfluid-finance/metadata/blob/master/main/networks/list.cjs) to this page? https://github.com/superfluid-finance/superfluid-console/blob/network/celo-mainnet/src/redux/protocolContracts.ts
> 
> Also, should be celo-mainnet as the slug as in the dashboard and latest metadata version no?

Regarding the slug, we don't use canonical names in the dashboard but there's a resolver @kasparkallas ?

**Comment by vmichalik** [comment]
>We could use the metadata for these though.

True, but let's do one thing at a time, queue this one for later 👍

**Review by vmichalik — APPROVED** [review]

**Review by kasparkallas — APPROVED** [review]
The Dashboard has a solution for canonical name handling and also chain ID handling which we could port to the Console. :)

Regarding URL slugs, let's keep them simple and beautiful. I don't want to remember whether it's "eth-goerli" or "goerli"; "celo-mainnet" or "celo"; "gnosis" or "xdai-mainnet"... "goerli", "celo", "gnosis" should suffice.

**Review by elvijsTDL — APPROVED** [review]

**Pull request merged**
