### PR TITLE
Feature/controlled flowing balance - Ready For Review

### PR DESCRIPTION
**Pull request by Seroxdesign**

### CODE REVIEW

**Comment by Seroxdesign** [comment]
Co-authored-by: Nitegeist <nitegeist@users.noreply.github.com>

**Comment by Seroxdesign** [comment]
https://user-images.githubusercontent.com/69639595/217279491-854d5f51-ec84-451e-94fb-ae7ae7e1273d.mp4

**Comment by sunnyjaycer** [comment]
Addresses #120

**Review by elvijsTDL — CHANGES_REQUESTED** [review]
The smart balances part is working fine, but the decimal places settings are doing nothing now, I think we should keep them working and have a seperate "smart flowing balance" setting , or remove altogether @kasparkallas @vmichalik

**Comment by vmichalik** [comment]
defer to @kasparkallas, but agree with your analysis @elvijsTDL

**Comment by Seroxdesign** [comment]
> The smart balances part is working fine, but the decimal places settings are doing nothing now, I think we should keep them working and have a seperate "smart flowing balance" setting , or remove altogether @kasparkallas @vmichalik

Could you clarify on what you mean by this?

What settings are not doing anything atm?

**Comment by vmichalik** [comment]
@Seroxdesign if you open the Console's settings cogwheel there is a selector for precision called "Ether Decimal Places" which is ignored with the smart flowing balances. @elvijsTDL's suggestion was that "smart flowing" could be an additional option instead of just removing the decimal precision options.

**Comment by Seroxdesign** [comment]
> @Seroxdesign if you open the Console's settings cogwheel there is a selector for precision called "Ether Decimal Places" which is ignored with the smart flowing balances. @elvijsTDL's suggestion was that "smart flowing" could be an additional option instead of just removing the decimal precision options.

How about I make the smart flowing balance a setting in the ethers decimal places?

Example:
aa

@vmichalik

**Comment by Seroxdesign** [comment]
closed by:

https://github.com/superfluid-finance/superfluid-console/pull/154

**Pull request closed without merging**
