### PR TITLE
Smart-flowing-balance option

### PR DESCRIPTION
**Pull request by Seroxdesign**
## Closes:  https://github.com/superfluid-finance/superfluid-console/pull/147  ## Addresses:  https://github.com/superfluid-finance/superfluid-console/issues/120

I've set the default behaviour to be same as app, you can make it smart flowing in the app bar

### CODE REVIEW

**Comment by Seroxdesign** [comment]
https://user-images.githubusercontent.com/69639595/219432204-6963512b-2579-4203-9155-bf2be752e1e3.mp4

@vmichalik @elvijsTDL

**Comment by elvijsTDL** [comment]
@Seroxdesign the flowing balances seem to be broken for me 

https://user-images.githubusercontent.com/77115130/220298003-71d02f87-5c2f-4a27-9553-f2a2b889a7dd.mov

**Comment by Seroxdesign** [comment]
https://user-images.githubusercontent.com/69639595/220375472-4296711d-8db7-4aaa-9bbd-da7298c08b18.mp4

Issue is resolved
@elvijsTDL

**Review by elvijsTDL — APPROVED** [review]
LGTM 👍

**Review by kasparkallas — APPROVED** [review]

**Pull request merged**
