### PR TITLE
Aggregate stats for account and super token pages.

### PR DESCRIPTION
**Pull request by Mikkoun**
**Super token page**
* Stream and index data section
* Total streamed, distributed, transferred and supply section

**Account page**
* Balances section

### CODE REVIEW

**Comment by Mikkoun** [comment]
@vmichalik Please check if you like the design. It was really hard to solve account page balances because it is so different for every account.

**Comment by kasparkallas** [comment]
Maybe filter out zeroes from the token summary? (Not the "super tokens" page.)

**Comment by vmichalik** [comment]
Definitely lots to work with here, nice one!

Nothing really to add!:
- filter out zeroes as suggested by kaspar

Observation:
- total supply numbers look really strange at first glance, but it's quite cool when you think about it!
- we might want to think about implementing the multi network view for accounts here at some point, perhaps using the same filtering we're planning for the user dashboard

**Comment by elvijsTDL** [comment]
Could we add a header for the super token balances in the accounts page? From the first glance it is not really clear that those are the token balances , could be incoming/outgoing streamed amount too since we use the same format for those
Screenshot 2022-04-19 at 13 00 50

**Review by kasparkallas — APPROVED** [review]

**Pull request merged**
