### PR TITLE
unix timpstamp

### PR DESCRIPTION
**Pull request by mindsgn**
added Unix timestamp to tooltip

### CODE REVIEW

**Comment by sunnyjaycer** [comment]
Addresses #134

**Comment by mindsgn** [comment]
hey @sunnyjaycer / @Mikkoun. just would like to checkin about this pr.

**Comment by vmichalik** [comment]
please bear with us @mindsgn, we will aim to review this within the week

**Review by elvijsTDL — APPROVED** [review]
Renamed , unix: to Timestamp: , other than that LGTM 👍

**Review by kasparkallas — APPROVED** [review]

**Pull request merged**
