### PR TITLE
Issue #144

### PR DESCRIPTION
**Pull request by UmerHA**
This PR addresses issue #144 and adds the net flow to the account page

### CODE REVIEW

**Comment by elvijsTDL** [comment]
@UmerHA I am not seeing no net flows in the Accounts pages, maybe you forgot to push something? 
Screenshot 2023-02-15 at 12 35 24

**Comment by UmerHA** [comment]
@elvijsTDL You have to open the Super Tokens tab, as net flows are per super token, not per stream.

**Comment by elvijsTDL** [comment]
@UmerHA Got it thanks

@vmichalik Was the ticket meant for the the super token tab or should it also show up next to the balances at the top of the accounts page?

**Comment by vmichalik** [comment]
@elvijsTDL it's a good question, I had intended it to go next to the super token chips in the balances section, however re-reading, it was poorly specified

we can improve our process to account for this, but in general the bounty was completed per the instructions 

@UmerHA if you'd like to continue by adding the flow rates next to the chips in the balances section, that would be appreciated, however I wouldn't make it a condition for bounty payout

**Comment by UmerHA** [comment]
@vmichalik Sure - done! 

Superfluid_Result

As a side note: I had discussed with Sunny from your team that the ticket was meant for the super token tab. I sent the following mock-up and he agreed:
Superfluid_NetBalances

**Comment by vmichalik** [comment]
Thanks a bunch @UmerHA!

**Comment by UmerHA** [comment]
Hi @vmichalik Is there anything else to do here?

The cypress tests seem to work on my machine:
image

**Comment by vmichalik** [comment]
Nope! We need to queue up doing some final code reviews before merging but @sunnyjaycer will be in touch for bounty payout in any case 🎉

**Comment by elvijsTDL** [comment]
Because of the way the balances are shown having the net flows for wallets who have a lot of balances it might overlay each other or go out of the screen and not be visible , really easy to reproduce if you use the 18 decimal setting 
Screenshot 2023-02-17 at 09 59 43

**Review by kasparkallas — APPROVED** [review]

**Review by elvijsTDL — APPROVED** [review]

**Pull request merged**
